// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTful_API_Development_dotNET_Eight.Data;

#nullable disable

namespace RESTful_API_Development_dotNET_Eight.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTful_API_Development_dotNET_Eight.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "Nike",
                            Color = "Blue",
                            Gender = "Male",
                            Price = 20.0,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "Adidas",
                            Color = "Red",
                            Gender = "Female",
                            Price = 25.0,
                            Size = 7
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Puma",
                            Color = "Green",
                            Gender = "Male",
                            Price = 30.0,
                            Size = 12
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "Reebok",
                            Color = "White",
                            Gender = "Male",
                            Price = 15.0,
                            Size = 9
                        },
                        new
                        {
                            ShirtId = 5,
                            Brand = "Under Armour",
                            Color = "Purple",
                            Gender = "Female",
                            Price = 22.0,
                            Size = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
